import { Outfit } from "next/font/google";
import "./globals.css";
import Navber from "@/components/Navber";
import Footer from "@/components/Footer";


const out= Outfit({

  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" data-theme="light"
      className={`${out.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#230D41FF]">
        <Navber></Navber>
        <main>
          {children}
        </main>
        <Footer></Footer>
        </body>
    </html>
  );
}
