import { Outfit } from "next/font/google";
import "./globals.css";

import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";
import Nav from "@/components/Nav";



const out= Outfit({

  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" data-theme="light"
      className={`${out.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#230D41FF]">  
      
   
        <ToastContainer />
        
      
        <Nav></Nav>
        <main className=" max-w-11/12 mx-auto">
    
          {children}
        </main>
        <Footer></Footer>
        </body>
    </html>
  );
}
